/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.8
 * Generated at: 2025-06-19 13:28:13 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class Main_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"zh-CN\">\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("    <title>职工管理系统</title>\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css\">\r\n");
      out.write("    <style>\r\n");
      out.write("        * {\r\n");
      out.write("            margin: 0;\r\n");
      out.write("            padding: 0;\r\n");
      out.write("            box-sizing: border-box;\r\n");
      out.write("            font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        :root {\r\n");
      out.write("            --primary: #1a73e8;\r\n");
      out.write("            --primary-dark: #0d47a1;\r\n");
      out.write("            --secondary: #f5f8fa;\r\n");
      out.write("            --accent: #34a853;\r\n");
      out.write("            --warning: #fbbc05;\r\n");
      out.write("            --danger: #ea4335;\r\n");
      out.write("            --text: #202124;\r\n");
      out.write("            --text-light: #5f6368;\r\n");
      out.write("            --card-shadow: 0 4px 12px rgba(0, 0, 0, 0.08);\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        body {\r\n");
      out.write("            background-color: #f8f9fa;\r\n");
      out.write("            color: var(--text);\r\n");
      out.write("            line-height: 1.6;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        /* Header Styles */\r\n");
      out.write("        header {\r\n");
      out.write("            background: linear-gradient(135deg, var(--primary), var(--primary-dark));\r\n");
      out.write("            color: white;\r\n");
      out.write("            padding: 1rem 0;\r\n");
      out.write("            box-shadow: 0 2px 10px rgba(0, 0, 0, 0.1);\r\n");
      out.write("            position: sticky;\r\n");
      out.write("            top: 0;\r\n");
      out.write("            z-index: 100;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        .header-container {\r\n");
      out.write("            max-width: 1200px;\r\n");
      out.write("            margin: 0 auto;\r\n");
      out.write("            padding: 0 2rem;\r\n");
      out.write("            display: flex;\r\n");
      out.write("            justify-content: space-between;\r\n");
      out.write("            align-items: center;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        .logo {\r\n");
      out.write("            display: flex;\r\n");
      out.write("            align-items: center;\r\n");
      out.write("            gap: 0.75rem;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        .logo-icon {\r\n");
      out.write("            font-size: 2rem;\r\n");
      out.write("            color: #fff;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        .logo h1 {\r\n");
      out.write("            font-size: 1.5rem;\r\n");
      out.write("            font-weight: 600;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        .nav-links {\r\n");
      out.write("            display: flex;\r\n");
      out.write("            gap: 1.5rem;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        .nav-links a {\r\n");
      out.write("            color: rgba(255, 255, 255, 0.9);\r\n");
      out.write("            text-decoration: none;\r\n");
      out.write("            font-weight: 500;\r\n");
      out.write("            padding: 0.5rem 0.75rem;\r\n");
      out.write("            border-radius: 4px;\r\n");
      out.write("            transition: all 0.3s ease;\r\n");
      out.write("            display: flex;\r\n");
      out.write("            align-items: center;\r\n");
      out.write("            gap: 0.5rem;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        .nav-links a:hover {\r\n");
      out.write("            background: rgba(255, 255, 255, 0.15);\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        .nav-links a i {\r\n");
      out.write("            font-size: 1.1rem;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        /* Main Content */\r\n");
      out.write("        main {\r\n");
      out.write("            max-width: 1200px;\r\n");
      out.write("            margin: 2rem auto;\r\n");
      out.write("            padding: 0 2rem;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        .welcome-section {\r\n");
      out.write("            background: white;\r\n");
      out.write("            border-radius: 12px;\r\n");
      out.write("            padding: 2.5rem;\r\n");
      out.write("            margin-bottom: 2.5rem;\r\n");
      out.write("            box-shadow: var(--card-shadow);\r\n");
      out.write("            text-align: center;\r\n");
      out.write("            position: relative;\r\n");
      out.write("            overflow: hidden;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        .welcome-section::before {\r\n");
      out.write("            content: '';\r\n");
      out.write("            position: absolute;\r\n");
      out.write("            top: 0;\r\n");
      out.write("            left: 0;\r\n");
      out.write("            width: 100%;\r\n");
      out.write("            height: 5px;\r\n");
      out.write("            background: linear-gradient(90deg, var(--primary), var(--accent));\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        .welcome-section h2 {\r\n");
      out.write("            font-size: 2rem;\r\n");
      out.write("            margin-bottom: 1rem;\r\n");
      out.write("            color: var(--primary-dark);\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        .welcome-section p {\r\n");
      out.write("            color: var(--text-light);\r\n");
      out.write("            max-width: 700px;\r\n");
      out.write("            margin: 0 auto 1.5rem;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        .stats-container {\r\n");
      out.write("            display: flex;\r\n");
      out.write("            justify-content: center;\r\n");
      out.write("            gap: 1.5rem;\r\n");
      out.write("            margin-top: 1.5rem;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        .stat-card {\r\n");
      out.write("            background: var(--secondary);\r\n");
      out.write("            border-radius: 8px;\r\n");
      out.write("            padding: 1.25rem;\r\n");
      out.write("            min-width: 150px;\r\n");
      out.write("            text-align: center;\r\n");
      out.write("            transition: transform 0.3s ease;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        .stat-card:hover {\r\n");
      out.write("            transform: translateY(-5px);\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        .stat-value {\r\n");
      out.write("            font-size: 2rem;\r\n");
      out.write("            font-weight: 700;\r\n");
      out.write("            color: var(--primary);\r\n");
      out.write("            margin-bottom: 0.5rem;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        .stat-label {\r\n");
      out.write("            color: var(--text-light);\r\n");
      out.write("            font-size: 0.9rem;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        /* Features Section */\r\n");
      out.write("        .features-section {\r\n");
      out.write("            margin-bottom: 2.5rem;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        .section-title {\r\n");
      out.write("            font-size: 1.75rem;\r\n");
      out.write("            margin-bottom: 1.5rem;\r\n");
      out.write("            color: var(--primary-dark);\r\n");
      out.write("            position: relative;\r\n");
      out.write("            padding-bottom: 0.75rem;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        .section-title::after {\r\n");
      out.write("            content: '';\r\n");
      out.write("            position: absolute;\r\n");
      out.write("            bottom: 0;\r\n");
      out.write("            left: 0;\r\n");
      out.write("            width: 60px;\r\n");
      out.write("            height: 4px;\r\n");
      out.write("            background: var(--primary);\r\n");
      out.write("            border-radius: 2px;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        .features-grid {\r\n");
      out.write("            display: grid;\r\n");
      out.write("            grid-template-columns: repeat(auto-fit, minmax(280px, 1fr));\r\n");
      out.write("            gap: 1.5rem;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        .feature-card {\r\n");
      out.write("            background: white;\r\n");
      out.write("            border-radius: 12px;\r\n");
      out.write("            overflow: hidden;\r\n");
      out.write("            box-shadow: var(--card-shadow);\r\n");
      out.write("            transition: all 0.3s ease;\r\n");
      out.write("            display: flex;\r\n");
      out.write("            flex-direction: column;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        .feature-card:hover {\r\n");
      out.write("            transform: translateY(-5px);\r\n");
      out.write("            box-shadow: 0 8px 16px rgba(0, 0, 0, 0.1);\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        .card-header {\r\n");
      out.write("            background: linear-gradient(135deg, var(--primary), var(--primary-dark));\r\n");
      out.write("            color: white;\r\n");
      out.write("            padding: 1.5rem;\r\n");
      out.write("            text-align: center;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        .card-header i {\r\n");
      out.write("            font-size: 2.5rem;\r\n");
      out.write("            margin-bottom: 1rem;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        .card-header h3 {\r\n");
      out.write("            font-size: 1.25rem;\r\n");
      out.write("            font-weight: 600;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        .card-body {\r\n");
      out.write("            padding: 1.5rem;\r\n");
      out.write("            flex-grow: 1;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        .card-body p {\r\n");
      out.write("            color: var(--text-light);\r\n");
      out.write("            margin-bottom: 1.5rem;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        .btn {\r\n");
      out.write("            display: inline-block;\r\n");
      out.write("            padding: 0.75rem 1.5rem;\r\n");
      out.write("            background: var(--primary);\r\n");
      out.write("            color: white;\r\n");
      out.write("            text-decoration: none;\r\n");
      out.write("            border-radius: 6px;\r\n");
      out.write("            font-weight: 500;\r\n");
      out.write("            transition: all 0.3s ease;\r\n");
      out.write("            border: none;\r\n");
      out.write("            cursor: pointer;\r\n");
      out.write("            text-align: center;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        .btn:hover {\r\n");
      out.write("            background: var(--primary-dark);\r\n");
      out.write("            transform: translateY(-2px);\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        .btn-outline {\r\n");
      out.write("            background: transparent;\r\n");
      out.write("            border: 2px solid var(--primary);\r\n");
      out.write("            color: var(--primary);\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        .btn-outline:hover {\r\n");
      out.write("            background: var(--primary);\r\n");
      out.write("            color: white;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        /* Footer */\r\n");
      out.write("        footer {\r\n");
      out.write("            background: var(--primary-dark);\r\n");
      out.write("            color: rgba(255, 255, 255, 0.8);\r\n");
      out.write("            padding: 2.5rem 0;\r\n");
      out.write("            margin-top: 3rem;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        .footer-container {\r\n");
      out.write("            max-width: 1200px;\r\n");
      out.write("            margin: 0 auto;\r\n");
      out.write("            padding: 0 2rem;\r\n");
      out.write("            display: flex;\r\n");
      out.write("            flex-direction: column;\r\n");
      out.write("            align-items: center;\r\n");
      out.write("            text-align: center;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        .footer-logo {\r\n");
      out.write("            font-size: 1.5rem;\r\n");
      out.write("            font-weight: 600;\r\n");
      out.write("            margin-bottom: 1.5rem;\r\n");
      out.write("            color: white;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        .copyright {\r\n");
      out.write("            font-size: 0.9rem;\r\n");
      out.write("            margin-top: 1.5rem;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        /* Responsive Design */\r\n");
      out.write("        @media (max-width: 768px) {\r\n");
      out.write("            .header-container {\r\n");
      out.write("                flex-direction: column;\r\n");
      out.write("                gap: 1rem;\r\n");
      out.write("            }\r\n");
      out.write("            \r\n");
      out.write("            .stats-container {\r\n");
      out.write("                flex-wrap: wrap;\r\n");
      out.write("            }\r\n");
      out.write("            \r\n");
      out.write("            .welcome-section {\r\n");
      out.write("                padding: 1.5rem;\r\n");
      out.write("            }\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        @media (max-width: 480px) {\r\n");
      out.write("            .nav-links {\r\n");
      out.write("                flex-wrap: wrap;\r\n");
      out.write("                justify-content: center;\r\n");
      out.write("            }\r\n");
      out.write("            \r\n");
      out.write("            .feature-card {\r\n");
      out.write("                margin-bottom: 1.5rem;\r\n");
      out.write("            }\r\n");
      out.write("        }\r\n");
      out.write("    </style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("    <!-- Header -->\r\n");
      out.write("    <header>\r\n");
      out.write("        <div class=\"header-container\">\r\n");
      out.write("            <div class=\"logo\">\r\n");
      out.write("                <i class=\"fas fa-users logo-icon\"></i>\r\n");
      out.write("                <h1>职工管理系统</h1>\r\n");
      out.write("            </div>\r\n");
      out.write("            <nav class=\"nav-links\">\r\n");
      out.write("                <a href=\"#\"><i class=\"fas fa-user-plus\"></i> 注册</a>\r\n");
      out.write("                <a href=\"#\"><i class=\"fas fa-sign-in-alt\"></i> 登录</a>\r\n");
      out.write("                <a href=\"#\"><i class=\"fas fa-building\"></i> 我的部门</a>\r\n");
      out.write("            </nav>\r\n");
      out.write("        </div>\r\n");
      out.write("    </header>\r\n");
      out.write("    \r\n");
      out.write("    <!-- Main Content -->\r\n");
      out.write("    <main>\r\n");
      out.write("        <section class=\"welcome-section\">\r\n");
      out.write("            <h2>欢迎使用职工管理系统</h2>\r\n");
      out.write("            <p>高效、便捷的职工管理平台，提供考勤管理、请假审批、工资结算等一站式服务，助力企业高效管理人力资源。</p>\r\n");
      out.write("            \r\n");
      out.write("            <div class=\"stats-container\">\r\n");
      out.write("                <div class=\"stat-card\">\r\n");
      out.write("                    <div class=\"stat-value\">1,258</div>\r\n");
      out.write("                    <div class=\"stat-label\">在职职工</div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"stat-card\">\r\n");
      out.write("                    <div class=\"stat-value\">96%</div>\r\n");
      out.write("                    <div class=\"stat-label\">本月出勤率</div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"stat-card\">\r\n");
      out.write("                    <div class=\"stat-value\">32</div>\r\n");
      out.write("                    <div class=\"stat-label\">待处理申请</div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"stat-card\">\r\n");
      out.write("                    <div class=\"stat-value\">15</div>\r\n");
      out.write("                    <div class=\"stat-label\">部门数量</div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </section>\r\n");
      out.write("        \r\n");
      out.write("        <section class=\"features-section\">\r\n");
      out.write("            <h2 class=\"section-title\">核心功能</h2>\r\n");
      out.write("            \r\n");
      out.write("            <div class=\"features-grid\">\r\n");
      out.write("                <!-- 考勤管理 -->\r\n");
      out.write("                <div class=\"feature-card\">\r\n");
      out.write("                    <div class=\"card-header\">\r\n");
      out.write("                        <i class=\"fas fa-calendar-check\"></i>\r\n");
      out.write("                        <h3>考勤管理</h3>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"card-body\">\r\n");
      out.write("                        <p>记录员工每日考勤情况，支持打卡管理、缺勤标记，生成考勤统计报表。</p>\r\n");
      out.write("                        <a href=\"#\" class=\"btn\">进入考勤</a>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                \r\n");
      out.write("                <!-- 请假/销假 -->\r\n");
      out.write("                <div class=\"feature-card\">\r\n");
      out.write("                    <div class=\"card-header\">\r\n");
      out.write("                        <i class=\"fas fa-file-medical\"></i>\r\n");
      out.write("                        <h3>请假/销假</h3>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"card-body\">\r\n");
      out.write("                        <p>在线提交请假申请，审批流程透明化，销假自动记录，请假历史一目了然。</p>\r\n");
      out.write("                        <a href=\"#\" class=\"btn\">申请请假</a>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                \r\n");
      out.write("                <!-- 规章制度 -->\r\n");
      out.write("                <div class=\"feature-card\">\r\n");
      out.write("                    <div class=\"card-header\">\r\n");
      out.write("                        <i class=\"fas fa-book\"></i>\r\n");
      out.write("                        <h3>规章制度</h3>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"card-body\">\r\n");
      out.write("                        <p>企业规章制度电子化，方便员工随时查阅，支持分类管理和关键词搜索。</p>\r\n");
      out.write("                        <a href=\"#\" class=\"btn\">查看制度</a>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                \r\n");
      out.write("                <!-- 通知公告 -->\r\n");
      out.write("                <div class=\"feature-card\">\r\n");
      out.write("                    <div class=\"card-header\">\r\n");
      out.write("                        <i class=\"fas fa-bullhorn\"></i>\r\n");
      out.write("                        <h3>通知公告</h3>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"card-body\">\r\n");
      out.write("                        <p>发布企业最新通知公告，支持定向推送，阅读状态跟踪，确保信息及时送达。</p>\r\n");
      out.write("                        <a href=\"#\" class=\"btn\">查看通知</a>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </section>\r\n");
      out.write("    </main>\r\n");
      out.write("    \r\n");
      out.write("    <!-- Footer -->\r\n");
      out.write("    <footer>\r\n");
      out.write("        <div class=\"footer-container\">\r\n");
      out.write("            <div class=\"footer-logo\">\r\n");
      out.write("                <i class=\"fas fa-users\"></i> 职工管理系统\r\n");
      out.write("            </div>\r\n");
      out.write("            <p>高效管理企业人力资源，提升组织管理效率</p>\r\n");
      out.write("            <div class=\"copyright\">\r\n");
      out.write("                &copy; 2023 职工管理系统 版权所有 | 设计开发: 企业IT部门\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </footer>\r\n");
      out.write("    \r\n");
      out.write("    <script>\r\n");
      out.write("        // 添加简单的动画效果\r\n");
      out.write("        document.addEventListener('DOMContentLoaded', function() {\r\n");
      out.write("            // 卡片进入动画\r\n");
      out.write("            const cards = document.querySelectorAll('.feature-card');\r\n");
      out.write("            cards.forEach((card, index) => {\r\n");
      out.write("                card.style.opacity = '0';\r\n");
      out.write("                card.style.transform = 'translateY(20px)';\r\n");
      out.write("                card.style.transition = 'opacity 0.5s ease, transform 0.5s ease';\r\n");
      out.write("                \r\n");
      out.write("                setTimeout(() => {\r\n");
      out.write("                    card.style.opacity = '1';\r\n");
      out.write("                    card.style.transform = 'translateY(0)';\r\n");
      out.write("                }, 300 + index * 150);\r\n");
      out.write("            });\r\n");
      out.write("            \r\n");
      out.write("            // 统计数字动画\r\n");
      out.write("            const stats = document.querySelectorAll('.stat-value');\r\n");
      out.write("            stats.forEach(stat => {\r\n");
      out.write("                const target = parseInt(stat.textContent);\r\n");
      out.write("                let current = 0;\r\n");
      out.write("                const increment = Math.ceil(target / 50);\r\n");
      out.write("                \r\n");
      out.write("                const timer = setInterval(() => {\r\n");
      out.write("                    current += increment;\r\n");
      out.write("                    if (current >= target) {\r\n");
      out.write("                        stat.textContent = target;\r\n");
      out.write("                        clearInterval(timer);\r\n");
      out.write("                    } else {\r\n");
      out.write("                        stat.textContent = current;\r\n");
      out.write("                    }\r\n");
      out.write("                }, 30);\r\n");
      out.write("            });\r\n");
      out.write("        });\r\n");
      out.write("    </script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
