/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.8
 * Generated at: 2025-06-20 06:06:19 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class register_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"zh-CN\">\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("    <title>职工管理系统 - 注册</title>\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css\">\r\n");
      out.write("    <style>\r\n");
      out.write("        * {\r\n");
      out.write("            margin: 0;\r\n");
      out.write("            padding: 0;\r\n");
      out.write("            box-sizing: border-box;\r\n");
      out.write("            font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        :root {\r\n");
      out.write("            --primary: #1a73e8;\r\n");
      out.write("            --primary-dark: #0d47a1;\r\n");
      out.write("            --secondary: #f5f8fa;\r\n");
      out.write("            --accent: #34a853;\r\n");
      out.write("            --warning: #fbbc05;\r\n");
      out.write("            --danger: #ea4335;\r\n");
      out.write("            --text: #202124;\r\n");
      out.write("            --text-light: #5f6368;\r\n");
      out.write("            --card-shadow: 0 4px 12px rgba(0, 0, 0, 0.08);\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        body {\r\n");
      out.write("            background-color: #f8f9fa;\r\n");
      out.write("            color: var(--text);\r\n");
      out.write("            line-height: 1.6;\r\n");
      out.write("            display: flex;\r\n");
      out.write("            flex-direction: column;\r\n");
      out.write("            min-height: 100vh;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        /* Header Styles */\r\n");
      out.write("        header {\r\n");
      out.write("            background: linear-gradient(135deg, var(--primary), var(--primary-dark));\r\n");
      out.write("            color: white;\r\n");
      out.write("            padding: 1rem 0;\r\n");
      out.write("            box-shadow: 0 2px 10px rgba(0, 0, 0, 0.1);\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        .header-container {\r\n");
      out.write("            max-width: 1200px;\r\n");
      out.write("            margin: 0 auto;\r\n");
      out.write("            padding: 0 2rem;\r\n");
      out.write("            display: flex;\r\n");
      out.write("            justify-content: space-between;\r\n");
      out.write("            align-items: center;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        .logo {\r\n");
      out.write("            display: flex;\r\n");
      out.write("            align-items: center;\r\n");
      out.write("            gap: 0.75rem;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        .logo-icon {\r\n");
      out.write("            font-size: 2rem;\r\n");
      out.write("            color: #fff;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        .logo h1 {\r\n");
      out.write("            font-size: 1.5rem;\r\n");
      out.write("            font-weight: 600;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        /* Main Content */\r\n");
      out.write("        main {\r\n");
      out.write("            flex: 1;\r\n");
      out.write("            display: flex;\r\n");
      out.write("            align-items: center;\r\n");
      out.write("            justify-content: center;\r\n");
      out.write("            padding: 2rem;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        .auth-container {\r\n");
      out.write("            max-width: 450px;\r\n");
      out.write("            width: 100%;\r\n");
      out.write("            background: white;\r\n");
      out.write("            border-radius: 12px;\r\n");
      out.write("            box-shadow: var(--card-shadow);\r\n");
      out.write("            overflow: hidden;\r\n");
      out.write("            position: relative;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        .auth-container::before {\r\n");
      out.write("            content: '';\r\n");
      out.write("            position: absolute;\r\n");
      out.write("            top: 0;\r\n");
      out.write("            left: 0;\r\n");
      out.write("            width: 100%;\r\n");
      out.write("            height: 5px;\r\n");
      out.write("            background: linear-gradient(90deg, var(--primary), var(--accent));\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        .auth-header {\r\n");
      out.write("            padding: 2rem;\r\n");
      out.write("            text-align: center;\r\n");
      out.write("            background: var(--secondary);\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        .auth-header i {\r\n");
      out.write("            font-size: 2.5rem;\r\n");
      out.write("            color: var(--primary);\r\n");
      out.write("            margin-bottom: 1rem;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        .auth-header h2 {\r\n");
      out.write("            font-size: 1.75rem;\r\n");
      out.write("            color: var(--primary-dark);\r\n");
      out.write("            margin-bottom: 0.5rem;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        .auth-header p {\r\n");
      out.write("            color: var(--text-light);\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        .auth-body {\r\n");
      out.write("            padding: 2rem;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        .form-group {\r\n");
      out.write("            margin-bottom: 1.5rem;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        .form-group label {\r\n");
      out.write("            display: block;\r\n");
      out.write("            margin-bottom: 0.5rem;\r\n");
      out.write("            color: var(--text);\r\n");
      out.write("            font-weight: 500;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        .form-control {\r\n");
      out.write("            width: 100%;\r\n");
      out.write("            padding: 0.75rem 1rem;\r\n");
      out.write("            border: 1px solid #ddd;\r\n");
      out.write("            border-radius: 6px;\r\n");
      out.write("            font-size: 1rem;\r\n");
      out.write("            transition: all 0.3s ease;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        .form-control:focus {\r\n");
      out.write("            border-color: var(--primary);\r\n");
      out.write("            outline: none;\r\n");
      out.write("            box-shadow: 0 0 0 3px rgba(26, 115, 232, 0.2);\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        .terms {\r\n");
      out.write("            display: flex;\r\n");
      out.write("            align-items: flex-start;\r\n");
      out.write("            margin: 1.5rem 0;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        .terms input {\r\n");
      out.write("            margin-right: 10px;\r\n");
      out.write("            margin-top: 3px;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        .terms label {\r\n");
      out.write("            color: var(--text-light);\r\n");
      out.write("            font-size: 0.9rem;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        .terms a {\r\n");
      out.write("            color: var(--primary);\r\n");
      out.write("            text-decoration: none;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        .terms a:hover {\r\n");
      out.write("            text-decoration: underline;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        .btn {\r\n");
      out.write("            display: inline-block;\r\n");
      out.write("            width: 100%;\r\n");
      out.write("            padding: 0.75rem;\r\n");
      out.write("            background: var(--primary);\r\n");
      out.write("            color: white;\r\n");
      out.write("            text-decoration: none;\r\n");
      out.write("            border-radius: 6px;\r\n");
      out.write("            font-weight: 500;\r\n");
      out.write("            font-size: 1rem;\r\n");
      out.write("            transition: all 0.3s ease;\r\n");
      out.write("            border: none;\r\n");
      out.write("            cursor: pointer;\r\n");
      out.write("            text-align: center;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        .btn:hover {\r\n");
      out.write("            background: var(--primary-dark);\r\n");
      out.write("            transform: translateY(-2px);\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        .auth-footer {\r\n");
      out.write("            text-align: center;\r\n");
      out.write("            margin-top: 1.5rem;\r\n");
      out.write("            color: var(--text-light);\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        .auth-footer a {\r\n");
      out.write("            color: var(--primary);\r\n");
      out.write("            text-decoration: none;\r\n");
      out.write("            font-weight: 500;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        .auth-footer a:hover {\r\n");
      out.write("            text-decoration: underline;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        /* Footer */\r\n");
      out.write("        footer {\r\n");
      out.write("            background: var(--primary-dark);\r\n");
      out.write("            color: rgba(255, 255, 255, 0.8);\r\n");
      out.write("            padding: 1.5rem 0;\r\n");
      out.write("            text-align: center;\r\n");
      out.write("            font-size: 0.9rem;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        /* Responsive Design */\r\n");
      out.write("        @media (max-width: 480px) {\r\n");
      out.write("            .auth-container {\r\n");
      out.write("                max-width: 100%;\r\n");
      out.write("            }\r\n");
      out.write("            \r\n");
      out.write("            .auth-header, .auth-body {\r\n");
      out.write("                padding: 1.5rem;\r\n");
      out.write("            }\r\n");
      out.write("        }\r\n");
      out.write("    </style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("    <!-- Header -->\r\n");
      out.write("    <header>\r\n");
      out.write("        <div class=\"header-container\">\r\n");
      out.write("            <div class=\"logo\">\r\n");
      out.write("                <i class=\"fas fa-users logo-icon\"></i>\r\n");
      out.write("                <h1>职工管理系统</h1>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </header>\r\n");
      out.write("    \r\n");
      out.write("    <!-- Main Content -->\r\n");
      out.write("    <main>\r\n");
      out.write("        <div class=\"auth-container\">\r\n");
      out.write("            <div class=\"auth-header\">\r\n");
      out.write("                <i class=\"fas fa-user-plus\"></i>\r\n");
      out.write("                <h2>创建新账号</h2>\r\n");
      out.write("                <p>加入我们的职工管理系统</p>\r\n");
      out.write("            </div>\r\n");
      out.write("            \r\n");
      out.write("            <div class=\"auth-body\">\r\n");
      out.write("                <form action=\"register\" method=\"post\" id=\"registerForm\">\r\n");
      out.write("                    <div class=\"form-group\">\r\n");
      out.write("                        <label for=\"username\">用户名</label>\r\n");
      out.write("                        <input type=\"text\" id=\"username\" name=\"username\" class=\"form-control\" placeholder=\"请输入用户名\" required>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    \r\n");
      out.write("                    <div class=\"form-group\">\r\n");
      out.write("                        <label for=\"email\">电子邮箱</label>\r\n");
      out.write("                        <input type=\"email\" id=\"email\" name=\"email\" class=\"form-control\" placeholder=\"请输入电子邮箱\" required>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    \r\n");
      out.write("                    <div class=\"form-group\">\r\n");
      out.write("                        <label for=\"password\">密码</label>\r\n");
      out.write("                        <input type=\"password\" id=\"password\" name=\"password\" class=\"form-control\" placeholder=\"请输入密码\" required>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    \r\n");
      out.write("                    <div class=\"form-group\">\r\n");
      out.write("                        <label for=\"confirm-password\">确认密码</label>\r\n");
      out.write("                        <input type=\"password\" id=\"confirm-password\" name=\"confirm_password\" class=\"form-control\" placeholder=\"请再次输入密码\" required>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    \r\n");
      out.write("                    <div class=\"terms\">\r\n");
      out.write("                        <input type=\"checkbox\" id=\"agree-terms\" name=\"agree_terms\" required>\r\n");
      out.write("                        <label for=\"agree-terms\">我已阅读并同意<a href=\"#\">用户协议</a>和<a href=\"#\">隐私政策</a></label>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    \r\n");
      out.write("                    <button type=\"submit\" class=\"btn btn-default\">注册</button>\r\n");
      out.write("                </form>\r\n");
      out.write("                \r\n");
      out.write("                <div class=\"auth-footer\">\r\n");
      out.write("                    已有账号? <a href=\"login.jsp\">立即登录</a>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </main>\r\n");
      out.write("    \r\n");
      out.write("    <!-- Footer -->\r\n");
      out.write("    <footer>\r\n");
      out.write("        &copy; 2023 职工管理系统 版权所有 | 设计开发: 企业IT部门\r\n");
      out.write("    </footer>\r\n");
      out.write("    \r\n");
      out.write("    <script>\r\n");
      out.write("        \r\n");
      out.write("        // 表单提交验证\r\n");
      out.write("        document.getElementById('registerForm').addEventListener('submit', function(event) {\r\n");
      out.write("            const password = document.getElementById('password').value;\r\n");
      out.write("            const confirmPassword = document.getElementById('confirm-password').value;\r\n");
      out.write("            \r\n");
      out.write("            if (password !== confirmPassword) {\r\n");
      out.write("                alert('两次输入的密码不一致！');\r\n");
      out.write("                event.preventDefault();\r\n");
      out.write("            }\r\n");
      out.write("            \r\n");
      out.write("            if (!document.getElementById('agree-terms').checked) {\r\n");
      out.write("                alert('请同意用户协议和隐私政策');\r\n");
      out.write("                event.preventDefault();\r\n");
      out.write("            }\r\n");
      out.write("        });\r\n");
      out.write("        \r\n");
      out.write("    </script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
