/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.8
 * Generated at: 2025-06-20 00:45:15 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.captcha;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("\t<head>\r\n");
      out.write("\t\t<meta charset=\"UTF-8\">\r\n");
      out.write("\t\t<title>我的校园</title>\r\n");
      out.write("\t\t<link rel=\"stylesheet\" href=\"bootstrap-3.3.5-dist/css/bootstrap.min.css\">\r\n");
      out.write("\t\t<script type=\"text/javascript\" src=\"bootstrap-3.3.5-dist/js/jquery-1.11.3.js\"></script>\r\n");
      out.write("\t\t<script type=\"text/javascript\" src=\"bootstrap-3.3.5-dist/js/bootstrap.min.js\"></script>\r\n");
      out.write("\t\t<style type=\"text/css\">\r\n");
      out.write("\t\t\tli{\r\n");
      out.write("\t\t\t\tline-height: 35px;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t</style>\r\n");
      out.write("\t</head>\r\n");
      out.write("\t<body>\r\n");
      out.write("\t\t <div class=\"container-fluid\">\r\n");
      out.write("\t\t     <nav class=\"navbar navbar-default\" style=\"margin-bottom: 2px;\">\r\n");
      out.write("\t\t\t\t  <div class=\"container-fluid\">\r\n");
      out.write("\t\t\t\t    <!-- Brand and toggle get grouped for better mobile display -->\r\n");
      out.write("\t\t\t\t    <div class=\"navbar-header\">\r\n");
      out.write("\t\t\t\t      <button type=\"button\" class=\"navbar-toggle collapsed\" data-toggle=\"collapse\" data-target=\"#bs-example-navbar-collapse-1\" aria-expanded=\"false\">\r\n");
      out.write("\t\t\t\t        <span class=\"sr-only\">Toggle navigation</span>\r\n");
      out.write("\t\t\t\t        <span class=\"icon-bar\"></span>\r\n");
      out.write("\t\t\t\t        <span class=\"icon-bar\"></span>\r\n");
      out.write("\t\t\t\t        <span class=\"icon-bar\"></span>\r\n");
      out.write("\t\t\t\t      </button>\r\n");
      out.write("\t\t\t\t      <a href=\"#\">\r\n");
      out.write("\t\t\t\t      \t<img src=\"images/logo.png\" style=\"width: 50px;height: 50px;\">\r\n");
      out.write("\t\t\t\t      </a>\r\n");
      out.write("\t\t\t\t    </div>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t    <!-- Collect the nav links, forms, and other content for toggling -->\r\n");
      out.write("\t\t\t\t    <div class=\"collapse navbar-collapse\" id=\"bs-example-navbar-collapse-1\">\r\n");
      out.write("\t\t\t\t      <ul class=\"nav navbar-nav\">\r\n");
      out.write("\t\t\t\t        <li class=\"active\"><a href=\"#\">我的校友<span class=\"sr-only\">(current)</span></a></li>\r\n");
      out.write("\t\t\t\t        <li><a href=\"#\">校园趣事</a></li>\r\n");
      out.write("\t\t\t\t      </ul>\r\n");
      out.write("\t\t\t\t      <form class=\"navbar-form navbar-left\" style=\"margin-left: 270px;\">\r\n");
      out.write("\t\t\t\t        <div class=\"form-group\">\r\n");
      out.write("\t\t\t\t          <input type=\"text\" style=\"width: 350px;\" class=\"form-control\" placeholder=\"学校名称\">\r\n");
      out.write("\t\t\t\t        </div>\r\n");
      out.write("\t\t\t\t        <button type=\"submit\" class=\"btn btn-default\">搜索</button>\r\n");
      out.write("\t\t\t\t      </form>\r\n");
      out.write("\t\t\t\t      <ul class=\"nav navbar-nav navbar-right\">\r\n");
      out.write("\t\t\t\t        <li><a href=\"#\">登录</a></li>\r\n");
      out.write("\t\t\t\t        <li><a href=\"register.jsp\">注册</a></li>\r\n");
      out.write("\t\t\t\t        <li class=\"dropdown\">\r\n");
      out.write("\t\t\t\t          <a href=\"#\" class=\"dropdown-toggle\" data-toggle=\"dropdown\" role=\"button\" aria-haspopup=\"true\" aria-expanded=\"false\">我的<span class=\"caret\"></span></a>\r\n");
      out.write("\t\t\t\t          <ul class=\"dropdown-menu\">\r\n");
      out.write("\t\t\t\t            <li><a href=\"#\">我的校友</a></li>\r\n");
      out.write("\t\t\t\t            <li><a href=\"#\">校园趣事</a></li>\r\n");
      out.write("\t\t\t\t            <li role=\"separator\" class=\"divider\"></li>\r\n");
      out.write("\t\t\t\t            <li><a href=\"#\">退出</a></li>\r\n");
      out.write("\t\t\t\t          </ul>\r\n");
      out.write("\t\t\t\t        </li>\r\n");
      out.write("\t\t\t\t      </ul>\r\n");
      out.write("\t\t\t\t    </div><!-- /.navbar-collapse -->\r\n");
      out.write("\t\t\t\t  </div><!-- /.container-fluid -->\r\n");
      out.write("\t\t\t\t</nav>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t<!-- 轮播图 begin -->\r\n");
      out.write("\t\t\t\t<div id=\"carousel-example-generic\" class=\"carousel slide\" data-ride=\"carousel\">\r\n");
      out.write("\t\t\t\t\t  <!-- Indicators -->\r\n");
      out.write("\t\t\t\t\t  <ol class=\"carousel-indicators\">\r\n");
      out.write("\t\t\t\t\t    <li data-target=\"#carousel-example-generic\" data-slide-to=\"0\" class=\"active\"></li>\r\n");
      out.write("\t\t\t\t\t    <li data-target=\"#carousel-example-generic\" data-slide-to=\"1\"></li>\r\n");
      out.write("\t\t\t\t\t    <li data-target=\"#carousel-example-generic\" data-slide-to=\"2\"></li>\r\n");
      out.write("\t\t\t\t\t  </ol>\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t  <!-- Wrapper for slides -->\r\n");
      out.write("\t\t\t\t\t  <div class=\"carousel-inner\" role=\"listbox\">\r\n");
      out.write("\t\t\t\t\t    <div class=\"item\">\r\n");
      out.write("\t\t\t\t\t      <img src=\"images/csust.jpg\" width=\"100%\" style=\"height: 300px;\" alt=\"...\">\r\n");
      out.write("\t\t\t\t\t      <div class=\"carousel-caption\">\r\n");
      out.write("\t\t\t\t\t               心如\r\n");
      out.write("\t\t\t\t\t      </div>\r\n");
      out.write("\t\t\t\t\t    </div>\r\n");
      out.write("\t\t\t\t\t    <div class=\"item active\">\r\n");
      out.write("\t\t\t\t\t      <img src=\"images/ad3.jpg\" width=\"100%\" style=\"height: 300px;\" alt=\"...\">\r\n");
      out.write("\t\t\t\t\t      <div class=\"carousel-caption\">\r\n");
      out.write("\t\t\t\t\t              酒店\r\n");
      out.write("\t\t\t\t\t      </div>\r\n");
      out.write("\t\t\t\t\t    </div>\r\n");
      out.write("\t\t\t\t\t    <div class=\"item\">\r\n");
      out.write("\t\t\t\t\t      <img src=\"images/ad3.jpg\" width=\"100%\" style=\"height: 300px;\" alt=\"...\">\r\n");
      out.write("\t\t\t\t\t      <div class=\"carousel-caption\">\r\n");
      out.write("\t\t\t\t\t             电脑\r\n");
      out.write("\t\t\t\t\t      </div>\r\n");
      out.write("\t\t\t\t\t    </div>\r\n");
      out.write("\t\t\t\t\t  </div>\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t  <!-- Controls -->\r\n");
      out.write("\t\t\t\t\t  <a class=\"left carousel-control\" href=\"#carousel-example-generic\" role=\"button\" data-slide=\"prev\">\r\n");
      out.write("\t\t\t\t\t    <span class=\"glyphicon glyphicon-chevron-left\" aria-hidden=\"true\"></span>\r\n");
      out.write("\t\t\t\t\t    <span class=\"sr-only\">Previous</span>\r\n");
      out.write("\t\t\t\t\t  </a>\r\n");
      out.write("\t\t\t\t\t  <a class=\"right carousel-control\" href=\"#carousel-example-generic\" role=\"button\" data-slide=\"next\">\r\n");
      out.write("\t\t\t\t\t    <span class=\"glyphicon glyphicon-chevron-right\" aria-hidden=\"true\"></span>\r\n");
      out.write("\t\t\t\t\t    <span class=\"sr-only\">Next</span>\r\n");
      out.write("\t\t\t\t\t  </a>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<!-- 轮播图 end -->\r\n");
      out.write("\t\t</div>    \r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<div class=\"container\">     \r\n");
      out.write("\t\t   <div class=\"row\">\r\n");
      out.write("\t\t   \t\t<div class=\"col-md-8\">\r\n");
      out.write("\t\t   \t\t\t<h3>校友推荐<small>系统推荐</small></h3>\r\n");
      out.write("\t\t   \t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t\t\t  <div class=\"col-md-3\">\r\n");
      out.write("\t\t\t\t\t\t    <div class=\"thumbnail\">\r\n");
      out.write("\t\t\t\t\t\t      <img src=\"images/s1.png\" class=\"img-rounded\" alt=\"...\">\r\n");
      out.write("\t\t\t\t\t\t      <div class=\"caption\">\r\n");
      out.write("\t\t\t\t\t\t        <h3 style=\"margin-top: 0px;margin-bottom: 0px;\">张三丰<small>长沙理工</small></h3>\r\n");
      out.write("\t\t\t\t\t\t      </div>\r\n");
      out.write("\t\t\t\t\t\t    </div>\r\n");
      out.write("\t\t\t\t\t\t  </div>\r\n");
      out.write("\t\t\t\t\t\t  <div class=\"col-sm-4 col-md-3\">\r\n");
      out.write("\t\t\t\t\t\t    <div class=\"thumbnail\">\r\n");
      out.write("\t\t\t\t\t\t      <img src=\"images/s2.png\" class=\"img-rounded\" alt=\"...\">\r\n");
      out.write("\t\t\t\t\t\t      <div class=\"caption\">\r\n");
      out.write("\t\t\t\t\t\t        <h3 style=\"margin-top: 0px;margin-bottom: 0px;\">张三丰<small>长沙理工</small></h3>\r\n");
      out.write("\t\t\t\t\t\t      </div>\r\n");
      out.write("\t\t\t\t\t\t    </div>\r\n");
      out.write("\t\t\t\t\t\t  </div>\r\n");
      out.write("\t\t\t\t\t\t  <div class=\"col-sm-4 col-md-3\">\r\n");
      out.write("\t\t\t\t\t\t    <div class=\"thumbnail\">\r\n");
      out.write("\t\t\t\t\t\t      <img src=\"images/s1.png\" class=\"img-rounded\" alt=\"...\">\r\n");
      out.write("\t\t\t\t\t\t      <div class=\"caption\">\r\n");
      out.write("\t\t\t\t\t\t        <h3 style=\"margin-top: 0px;margin-bottom: 0px;\">张三丰<small>长沙理工</small></h3>\r\n");
      out.write("\t\t\t\t\t\t      </div>\r\n");
      out.write("\t\t\t\t\t\t    </div>\r\n");
      out.write("\t\t\t\t\t\t  </div>\r\n");
      out.write("\t\t\t\t\t\t \r\n");
      out.write("\t\t\t\t\t\t  <div class=\"col-sm-4 col-md-3\">\r\n");
      out.write("\t\t\t\t\t\t    <div class=\"thumbnail\">\r\n");
      out.write("\t\t\t\t\t\t      <img src=\"images/s1.png\" class=\"img-rounded\" alt=\"...\">\r\n");
      out.write("\t\t\t\t\t\t      <div class=\"caption\">\r\n");
      out.write("\t\t\t\t\t\t        <h3 style=\"margin-top: 0px;margin-bottom: 0px;\">张三丰<small>长沙理工</small></h3>\r\n");
      out.write("\t\t\t\t\t\t      </div>\r\n");
      out.write("\t\t\t\t\t\t    </div>\r\n");
      out.write("\t\t\t\t\t\t  </div>\r\n");
      out.write("\t\t\t\t\t\t  <div class=\"col-sm-4 col-md-3\">\r\n");
      out.write("\t\t\t\t\t\t    <div class=\"thumbnail\">\r\n");
      out.write("\t\t\t\t\t\t      <img src=\"images/s2.png\" class=\"img-rounded\" alt=\"...\">\r\n");
      out.write("\t\t\t\t\t\t      <div class=\"caption\">\r\n");
      out.write("\t\t\t\t\t\t        <h3 style=\"margin-top: 0px;margin-bottom: 0px;\">张三丰<small>长沙理工</small></h3>\r\n");
      out.write("\t\t\t\t\t\t      </div>\r\n");
      out.write("\t\t\t\t\t\t    </div>\r\n");
      out.write("\t\t\t\t\t\t  </div>\r\n");
      out.write("\t\t\t\t\t\t  <div class=\"col-sm-4 col-md-3\">\r\n");
      out.write("\t\t\t\t\t\t    <div class=\"thumbnail\">\r\n");
      out.write("\t\t\t\t\t\t      <img src=\"images/s2.png\" class=\"img-rounded\" alt=\"...\">\r\n");
      out.write("\t\t\t\t\t\t      <div class=\"caption\">\r\n");
      out.write("\t\t\t\t\t\t        <h3 style=\"margin-top: 0px;margin-bottom: 0px;\">张三丰<small>长沙理工</small></h3>\r\n");
      out.write("\t\t\t\t\t\t      </div>\r\n");
      out.write("\t\t\t\t\t\t    </div>\r\n");
      out.write("\t\t\t\t\t\t  </div>\r\n");
      out.write("\t\t\t\t\t\t  <div class=\"col-sm-4 col-md-3\">\r\n");
      out.write("\t\t\t\t\t\t    <div class=\"thumbnail\">\r\n");
      out.write("\t\t\t\t\t\t      <img src=\"images/s2.png\" class=\"img-rounded\" alt=\"...\">\r\n");
      out.write("\t\t\t\t\t\t      <div class=\"caption\">\r\n");
      out.write("\t\t\t\t\t\t        <h3 style=\"margin-top: 0px;margin-bottom: 0px;\">张三丰<small>长沙理工</small></h3>\r\n");
      out.write("\t\t\t\t\t\t      </div>\r\n");
      out.write("\t\t\t\t\t\t    </div>\r\n");
      out.write("\t\t\t\t\t\t  </div>\r\n");
      out.write("\t\t\t\t\t\t  <div class=\"col-sm-4 col-md-3\">\r\n");
      out.write("\t\t\t\t\t\t    <div class=\"thumbnail\">\r\n");
      out.write("\t\t\t\t\t\t      <img src=\"images/s2.png\" class=\"img-rounded\" alt=\"...\">\r\n");
      out.write("\t\t\t\t\t\t      <div class=\"caption\">\r\n");
      out.write("\t\t\t\t\t\t        <h3 style=\"margin-top: 0px;margin-bottom: 0px;\">张三丰<small>长沙理工</small></h3>\r\n");
      out.write("\t\t\t\t\t\t      </div>\r\n");
      out.write("\t\t\t\t\t\t    </div>\r\n");
      out.write("\t\t\t\t\t\t  </div>\r\n");
      out.write("\t\t\t\t\t\t  <div class=\"col-sm-4 col-md-3\">\r\n");
      out.write("\t\t\t\t\t\t    <div class=\"thumbnail\">\r\n");
      out.write("\t\t\t\t\t\t      <img src=\"images/s1.png\" class=\"img-rounded\" alt=\"...\">\r\n");
      out.write("\t\t\t\t\t\t      <div class=\"caption\">\r\n");
      out.write("\t\t\t\t\t\t        <h3 style=\"margin-top: 0px;margin-bottom: 0px;\">张三丰<small>长沙理工</small></h3>\r\n");
      out.write("\t\t\t\t\t\t      </div>\r\n");
      out.write("\t\t\t\t\t\t    </div>\r\n");
      out.write("\t\t\t\t\t\t  </div>\r\n");
      out.write("\t\t\t\t\t\t  <div class=\"col-sm-4 col-md-3\">\r\n");
      out.write("\t\t\t\t\t\t    <div class=\"thumbnail\">\r\n");
      out.write("\t\t\t\t\t\t      <img src=\"images/s2.png\" class=\"img-rounded\" alt=\"...\">\r\n");
      out.write("\t\t\t\t\t\t      <div class=\"caption\">\r\n");
      out.write("\t\t\t\t\t\t        <h3 style=\"margin-top: 0px;margin-bottom: 0px;\">张三丰<small>长沙理工</small></h3>\r\n");
      out.write("\t\t\t\t\t\t      </div>\r\n");
      out.write("\t\t\t\t\t\t    </div>\r\n");
      out.write("\t\t\t\t\t\t  </div>\r\n");
      out.write("\t\t\t\t\t\t  <div class=\"col-sm-4 col-md-3\">\r\n");
      out.write("\t\t\t\t\t\t    <div class=\"thumbnail\">\r\n");
      out.write("\t\t\t\t\t\t      <img src=\"images/s2.png\" class=\"img-rounded\" alt=\"...\">\r\n");
      out.write("\t\t\t\t\t\t      <div class=\"caption\">\r\n");
      out.write("\t\t\t\t\t\t        <h3 style=\"margin-top: 0px;margin-bottom: 0px;\">张三丰<small>长沙理工</small></h3>\r\n");
      out.write("\t\t\t\t\t\t      </div>\r\n");
      out.write("\t\t\t\t\t\t    </div>\r\n");
      out.write("\t\t\t\t\t\t  </div>\r\n");
      out.write("\t\t\t\t\t\t  <div class=\"col-sm-4 col-md-3\">\r\n");
      out.write("\t\t\t\t\t\t    <div class=\"thumbnail\">\r\n");
      out.write("\t\t\t\t\t\t      <img src=\"images/s2.png\" class=\"img-rounded\" alt=\"...\">\r\n");
      out.write("\t\t\t\t\t\t      <div class=\"caption\">\r\n");
      out.write("\t\t\t\t\t\t        <h3 style=\"margin-top: 0px;margin-bottom: 0px;\">张三丰<small>长沙理工</small></h3>\r\n");
      out.write("\t\t\t\t\t\t      </div>\r\n");
      out.write("\t\t\t\t\t\t    </div>\r\n");
      out.write("\t\t\t\t\t\t  </div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t   \t\t</div>\r\n");
      out.write("  \t\t\t\t<div class=\"col-md-4\" style=\"padding-left: 66px;padding-top: 30px;\">\r\n");
      out.write("  \t\t\t\t\t<h4><span class=\"glyphicon glyphicon-tags\" aria-hidden=\"true\"></span>&nbsp;校园趣事</h4>\r\n");
      out.write("  \t\t\t\t\t<hr>\r\n");
      out.write("  \t\t\t\t\t<ol>\r\n");
      out.write("  \t\t\t\t\t\t<li>美国防部：美军仍然保持着防御态势</li>\r\n");
      out.write("  \t\t\t\t\t\t<li>美国防部：美军仍然保持着防御态势</li>\r\n");
      out.write("  \t\t\t\t\t\t<li>美国防部：美军仍然保持着防御态势</li>\r\n");
      out.write("  \t\t\t\t\t\t<li>美国防部：美军仍然保持着防御态势</li>\r\n");
      out.write("  \t\t\t\t\t\t<li>美国防部：美军仍然保持着防御态势</li>\r\n");
      out.write("  \t\t\t\t\t\t<li>美国防部：美军仍然保持着防御态势</li>\r\n");
      out.write("  \t\t\t\t\t\t<li>美国防部：美军仍然保持着防御态势</li>\r\n");
      out.write("  \t\t\t\t\t\t<li>美国防部：美军仍然保持着防御态势</li>\r\n");
      out.write("  \t\t\t\t\t\t<li>美国防部：美军仍然保持着防御态势</li>\r\n");
      out.write("  \t\t\t\t\t</ol>\r\n");
      out.write("  \t\t\t\t</div>\r\n");
      out.write("\t\t   </div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<div class=\"container-fluid text-center\" style=\"background-color: #dbdbdb;padding-top: 20px;\">\r\n");
      out.write("\t\t  \t<p>© 2005-2025 ft.com, all rights reserved 方图教育</p>\r\n");
      out.write("\t\t  \t<p>违法和不良信息/涉未成年人/生活服务类专项有害信息投诉：13787134545</p>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
